// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Anime struct {
	ID            int64         `json:"id"`
	Name          string        `json:"name"`
	Type          string        `json:"type"`
	Summary       string        `json:"summary"`
	NumOfEpisodes sql.NullInt32 `json:"numOfEpisodes"`
	OtherNames    []string      `json:"otherNames"`
	Status        string        `json:"status"`
	Genre         []string      `json:"genre"`
	Released      int32         `json:"released"`
	CreatedAt     time.Time     `json:"createdAt"`
}

type Character struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	FromAnime       int64     `json:"fromAnime"`
	Intro           string    `json:"intro"`
	Characteristics []string  `json:"characteristics"`
	CreatedAt       time.Time `json:"createdAt"`
}

type Episode struct {
	ID          int64     `json:"id"`
	Number      int32     `json:"number"`
	Anime       int64     `json:"anime"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}
