// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package animepb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnimeServiceClient is the client API for AnimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnimeServiceClient interface {
	// Lists Animes with desired Criteria
	ListAnimes(ctx context.Context, in *ListAnimesRequest, opts ...grpc.CallOption) (*ListAnimesResponse, error)
	// Creates Anime with given data
	CreateAnime(ctx context.Context, in *CreateAnimeRequest, opts ...grpc.CallOption) (*CreateAnimeResponse, error)
	// Get Anime with given ID
	GetAnime(ctx context.Context, in *GetAnimeRequest, opts ...grpc.CallOption) (*GetAnimeResponse, error)
	// Updates an existing Anime with given ID. Note that some properties such as ID are not modifiable.
	UpdateAnime(ctx context.Context, in *UpdateAnimeRequest, opts ...grpc.CallOption) (*Anime, error)
	// Delete
	DeleteAnime(ctx context.Context, in *DeleteAnimeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type animeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimeServiceClient(cc grpc.ClientConnInterface) AnimeServiceClient {
	return &animeServiceClient{cc}
}

func (c *animeServiceClient) ListAnimes(ctx context.Context, in *ListAnimesRequest, opts ...grpc.CallOption) (*ListAnimesResponse, error) {
	out := new(ListAnimesResponse)
	err := c.cc.Invoke(ctx, "/otaku.anime.AnimeService/ListAnimes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeServiceClient) CreateAnime(ctx context.Context, in *CreateAnimeRequest, opts ...grpc.CallOption) (*CreateAnimeResponse, error) {
	out := new(CreateAnimeResponse)
	err := c.cc.Invoke(ctx, "/otaku.anime.AnimeService/CreateAnime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeServiceClient) GetAnime(ctx context.Context, in *GetAnimeRequest, opts ...grpc.CallOption) (*GetAnimeResponse, error) {
	out := new(GetAnimeResponse)
	err := c.cc.Invoke(ctx, "/otaku.anime.AnimeService/GetAnime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeServiceClient) UpdateAnime(ctx context.Context, in *UpdateAnimeRequest, opts ...grpc.CallOption) (*Anime, error) {
	out := new(Anime)
	err := c.cc.Invoke(ctx, "/otaku.anime.AnimeService/UpdateAnime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeServiceClient) DeleteAnime(ctx context.Context, in *DeleteAnimeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/otaku.anime.AnimeService/DeleteAnime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeServiceServer is the server API for AnimeService service.
// All implementations must embed UnimplementedAnimeServiceServer
// for forward compatibility
type AnimeServiceServer interface {
	// Lists Animes with desired Criteria
	ListAnimes(context.Context, *ListAnimesRequest) (*ListAnimesResponse, error)
	// Creates Anime with given data
	CreateAnime(context.Context, *CreateAnimeRequest) (*CreateAnimeResponse, error)
	// Get Anime with given ID
	GetAnime(context.Context, *GetAnimeRequest) (*GetAnimeResponse, error)
	// Updates an existing Anime with given ID. Note that some properties such as ID are not modifiable.
	UpdateAnime(context.Context, *UpdateAnimeRequest) (*Anime, error)
	// Delete
	DeleteAnime(context.Context, *DeleteAnimeRequest) (*empty.Empty, error)
	mustEmbedUnimplementedAnimeServiceServer()
}

// UnimplementedAnimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnimeServiceServer struct {
}

func (UnimplementedAnimeServiceServer) ListAnimes(context.Context, *ListAnimesRequest) (*ListAnimesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnimes not implemented")
}
func (UnimplementedAnimeServiceServer) CreateAnime(context.Context, *CreateAnimeRequest) (*CreateAnimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnime not implemented")
}
func (UnimplementedAnimeServiceServer) GetAnime(context.Context, *GetAnimeRequest) (*GetAnimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnime not implemented")
}
func (UnimplementedAnimeServiceServer) UpdateAnime(context.Context, *UpdateAnimeRequest) (*Anime, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnime not implemented")
}
func (UnimplementedAnimeServiceServer) DeleteAnime(context.Context, *DeleteAnimeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnime not implemented")
}
func (UnimplementedAnimeServiceServer) mustEmbedUnimplementedAnimeServiceServer() {}

// UnsafeAnimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimeServiceServer will
// result in compilation errors.
type UnsafeAnimeServiceServer interface {
	mustEmbedUnimplementedAnimeServiceServer()
}

func RegisterAnimeServiceServer(s grpc.ServiceRegistrar, srv AnimeServiceServer) {
	s.RegisterService(&AnimeService_ServiceDesc, srv)
}

func _AnimeService_ListAnimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).ListAnimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otaku.anime.AnimeService/ListAnimes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).ListAnimes(ctx, req.(*ListAnimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimeService_CreateAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).CreateAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otaku.anime.AnimeService/CreateAnime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).CreateAnime(ctx, req.(*CreateAnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimeService_GetAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).GetAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otaku.anime.AnimeService/GetAnime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).GetAnime(ctx, req.(*GetAnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimeService_UpdateAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).UpdateAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otaku.anime.AnimeService/UpdateAnime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).UpdateAnime(ctx, req.(*UpdateAnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimeService_DeleteAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).DeleteAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otaku.anime.AnimeService/DeleteAnime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).DeleteAnime(ctx, req.(*DeleteAnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnimeService_ServiceDesc is the grpc.ServiceDesc for AnimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otaku.anime.AnimeService",
	HandlerType: (*AnimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAnimes",
			Handler:    _AnimeService_ListAnimes_Handler,
		},
		{
			MethodName: "CreateAnime",
			Handler:    _AnimeService_CreateAnime_Handler,
		},
		{
			MethodName: "GetAnime",
			Handler:    _AnimeService_GetAnime_Handler,
		},
		{
			MethodName: "UpdateAnime",
			Handler:    _AnimeService_UpdateAnime_Handler,
		},
		{
			MethodName: "DeleteAnime",
			Handler:    _AnimeService_DeleteAnime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anime.proto",
}
