// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: anime.proto

package animepb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defining the Enum Sort
type ListAnimesRequest_Sort int32

const (
	// Option to Sort by Name
	ListAnimesRequest_NAME ListAnimesRequest_Sort = 0
	// Option to sort by number of Episodes
	ListAnimesRequest_NUMOFEPISODES ListAnimesRequest_Sort = 1
	// Option to Sort by Rating
	ListAnimesRequest_RATING ListAnimesRequest_Sort = 2
)

// Enum value maps for ListAnimesRequest_Sort.
var (
	ListAnimesRequest_Sort_name = map[int32]string{
		0: "NAME",
		1: "NUMOFEPISODES",
		2: "RATING",
	}
	ListAnimesRequest_Sort_value = map[string]int32{
		"NAME":          0,
		"NUMOFEPISODES": 1,
		"RATING":        2,
	}
)

func (x ListAnimesRequest_Sort) Enum() *ListAnimesRequest_Sort {
	p := new(ListAnimesRequest_Sort)
	*p = x
	return p
}

func (x ListAnimesRequest_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListAnimesRequest_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_anime_proto_enumTypes[0].Descriptor()
}

func (ListAnimesRequest_Sort) Type() protoreflect.EnumType {
	return &file_anime_proto_enumTypes[0]
}

func (x ListAnimesRequest_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListAnimesRequest_Sort.Descriptor instead.
func (ListAnimesRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{1, 0}
}

// Defining the Enum Order
type ListAnimesRequest_Order int32

const (
	// Option for Ordering in Descending format
	ListAnimesRequest_DESCENDING ListAnimesRequest_Order = 0
	// Option for Ordering in Ascending format
	ListAnimesRequest_ASCENDING ListAnimesRequest_Order = 1
)

// Enum value maps for ListAnimesRequest_Order.
var (
	ListAnimesRequest_Order_name = map[int32]string{
		0: "DESCENDING",
		1: "ASCENDING",
	}
	ListAnimesRequest_Order_value = map[string]int32{
		"DESCENDING": 0,
		"ASCENDING":  1,
	}
)

func (x ListAnimesRequest_Order) Enum() *ListAnimesRequest_Order {
	p := new(ListAnimesRequest_Order)
	*p = x
	return p
}

func (x ListAnimesRequest_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListAnimesRequest_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_anime_proto_enumTypes[1].Descriptor()
}

func (ListAnimesRequest_Order) Type() protoreflect.EnumType {
	return &file_anime_proto_enumTypes[1]
}

func (x ListAnimesRequest_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListAnimesRequest_Order.Descriptor instead.
func (ListAnimesRequest_Order) EnumDescriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{1, 1}
}

// Structure of Anime Object
type Anime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name (Title) of the Anime
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Short description of Anime, at most 50 words
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Number of Episodes in the particular Anime
	NumOfEpisodes int32 `protobuf:"varint,4,opt,name=num_of_episodes,json=numOfEpisodes,proto3" json:"num_of_episodes,omitempty"`
	// Cast of that Anime
	Cast []string `protobuf:"bytes,5,rep,name=cast,proto3" json:"cast,omitempty"`
	// Status of the Anime
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Genre of the Anime
	Genre []string `protobuf:"bytes,7,rep,name=genre,proto3" json:"genre,omitempty"`
	// Time of Creating the Record for Anime
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Anime) Reset() {
	*x = Anime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Anime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anime) ProtoMessage() {}

func (x *Anime) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anime.ProtoReflect.Descriptor instead.
func (*Anime) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{0}
}

func (x *Anime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Anime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Anime) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Anime) GetNumOfEpisodes() int32 {
	if x != nil {
		return x.NumOfEpisodes
	}
	return 0
}

func (x *Anime) GetCast() []string {
	if x != nil {
		return x.Cast
	}
	return nil
}

func (x *Anime) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Anime) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *Anime) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Structure of ListAnimes Request
type ListAnimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Page number requested
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The option to sort by -
	Sort ListAnimesRequest_Sort `protobuf:"varint,2,opt,name=sort,proto3,enum=otaku.anime.ListAnimesRequest_Sort" json:"sort,omitempty"`
	// Order of Sorting - Ascending/Descending
	Order ListAnimesRequest_Order `protobuf:"varint,3,opt,name=order,proto3,enum=otaku.anime.ListAnimesRequest_Order" json:"order,omitempty"`
	// Filters for search or display
	Filter []string `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty"`
	// The substring for search query
	Search string `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *ListAnimesRequest) Reset() {
	*x = ListAnimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnimesRequest) ProtoMessage() {}

func (x *ListAnimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnimesRequest.ProtoReflect.Descriptor instead.
func (*ListAnimesRequest) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{1}
}

func (x *ListAnimesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAnimesRequest) GetSort() ListAnimesRequest_Sort {
	if x != nil {
		return x.Sort
	}
	return ListAnimesRequest_NAME
}

func (x *ListAnimesRequest) GetOrder() ListAnimesRequest_Order {
	if x != nil {
		return x.Order
	}
	return ListAnimesRequest_DESCENDING
}

func (x *ListAnimesRequest) GetFilter() []string {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListAnimesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// Structure of ListAnimes Response
type ListAnimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of Animes to be returned
	Animes []*Anime `protobuf:"bytes,1,rep,name=animes,proto3" json:"animes,omitempty"`
}

func (x *ListAnimesResponse) Reset() {
	*x = ListAnimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnimesResponse) ProtoMessage() {}

func (x *ListAnimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnimesResponse.ProtoReflect.Descriptor instead.
func (*ListAnimesResponse) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{2}
}

func (x *ListAnimesResponse) GetAnimes() []*Anime {
	if x != nil {
		return x.Animes
	}
	return nil
}

type CreateAnimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anime *Anime `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
}

func (x *CreateAnimeRequest) Reset() {
	*x = CreateAnimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeRequest) ProtoMessage() {}

func (x *CreateAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimeRequest) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAnimeRequest) GetAnime() *Anime {
	if x != nil {
		return x.Anime
	}
	return nil
}

type CreateAnimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateAnimeResponse) Reset() {
	*x = CreateAnimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeResponse) ProtoMessage() {}

func (x *CreateAnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimeResponse) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAnimeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAnimeRequest) Reset() {
	*x = GetAnimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeRequest) ProtoMessage() {}

func (x *GetAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeRequest.ProtoReflect.Descriptor instead.
func (*GetAnimeRequest) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{5}
}

func (x *GetAnimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anime *Anime `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
}

func (x *GetAnimeResponse) Reset() {
	*x = GetAnimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeResponse) ProtoMessage() {}

func (x *GetAnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeResponse.ProtoReflect.Descriptor instead.
func (*GetAnimeResponse) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{6}
}

func (x *GetAnimeResponse) GetAnime() *Anime {
	if x != nil {
		return x.Anime
	}
	return nil
}

type UpdateAnimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Anime *Anime `protobuf:"bytes,2,opt,name=anime,proto3" json:"anime,omitempty"`
}

func (x *UpdateAnimeRequest) Reset() {
	*x = UpdateAnimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnimeRequest) ProtoMessage() {}

func (x *UpdateAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnimeRequest) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAnimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAnimeRequest) GetAnime() *Anime {
	if x != nil {
		return x.Anime
	}
	return nil
}

type DeleteAnimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAnimeRequest) Reset() {
	*x = DeleteAnimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anime_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnimeRequest) ProtoMessage() {}

func (x *DeleteAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnimeRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnimeRequest) Descriptor() ([]byte, []int) {
	return file_anime_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAnimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_anime_proto protoreflect.FileDescriptor

var file_anime_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f,
	0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x05, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x66,
	0x5f, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x45, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x61, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0xa5, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x12, 0x3a, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x2f,
	0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x55, 0x4d, 0x4f, 0x46, 0x45, 0x50, 0x49, 0x53, 0x4f, 0x44, 0x45,
	0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x22,
	0x26, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x53, 0x43,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x53, 0x43, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x22, 0x40, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x05, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x22, 0x2a,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x05, 0x61, 0x6e, 0x69, 0x6d, 0x65,
	0x22, 0x53, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x61,
	0x6e, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x74, 0x61,
	0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x05,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x02, 0x69, 0x64,
	0x32, 0x85, 0x04, 0x0a, 0x0c, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x61, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x1e, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x73, 0x12, 0x6b, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x69, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x0a,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x3a, 0x05, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x12, 0x60, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x2e,
	0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x74,
	0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x62, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x32,
	0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x3a, 0x05, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x5f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x6f, 0x74, 0x61, 0x6b, 0x75, 0x2e, 0x61,
	0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6b, 0x61, 0x73, 0x68, 0x47, 0x69, 0x74, 0x32,
	0x31, 0x2f, 0x4f, 0x74, 0x61, 0x6b, 0x75, 0x5f, 0x41, 0x50, 0x49, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x3b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_anime_proto_rawDescOnce sync.Once
	file_anime_proto_rawDescData = file_anime_proto_rawDesc
)

func file_anime_proto_rawDescGZIP() []byte {
	file_anime_proto_rawDescOnce.Do(func() {
		file_anime_proto_rawDescData = protoimpl.X.CompressGZIP(file_anime_proto_rawDescData)
	})
	return file_anime_proto_rawDescData
}

var file_anime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_anime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_anime_proto_goTypes = []interface{}{
	(ListAnimesRequest_Sort)(0),  // 0: otaku.anime.ListAnimesRequest.Sort
	(ListAnimesRequest_Order)(0), // 1: otaku.anime.ListAnimesRequest.Order
	(*Anime)(nil),                // 2: otaku.anime.Anime
	(*ListAnimesRequest)(nil),    // 3: otaku.anime.ListAnimesRequest
	(*ListAnimesResponse)(nil),   // 4: otaku.anime.ListAnimesResponse
	(*CreateAnimeRequest)(nil),   // 5: otaku.anime.CreateAnimeRequest
	(*CreateAnimeResponse)(nil),  // 6: otaku.anime.CreateAnimeResponse
	(*GetAnimeRequest)(nil),      // 7: otaku.anime.GetAnimeRequest
	(*GetAnimeResponse)(nil),     // 8: otaku.anime.GetAnimeResponse
	(*UpdateAnimeRequest)(nil),   // 9: otaku.anime.UpdateAnimeRequest
	(*DeleteAnimeRequest)(nil),   // 10: otaku.anime.DeleteAnimeRequest
	(*empty.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_anime_proto_depIdxs = []int32{
	0,  // 0: otaku.anime.ListAnimesRequest.sort:type_name -> otaku.anime.ListAnimesRequest.Sort
	1,  // 1: otaku.anime.ListAnimesRequest.order:type_name -> otaku.anime.ListAnimesRequest.Order
	2,  // 2: otaku.anime.ListAnimesResponse.animes:type_name -> otaku.anime.Anime
	2,  // 3: otaku.anime.CreateAnimeRequest.anime:type_name -> otaku.anime.Anime
	2,  // 4: otaku.anime.GetAnimeResponse.anime:type_name -> otaku.anime.Anime
	2,  // 5: otaku.anime.UpdateAnimeRequest.anime:type_name -> otaku.anime.Anime
	3,  // 6: otaku.anime.AnimeService.ListAnimes:input_type -> otaku.anime.ListAnimesRequest
	5,  // 7: otaku.anime.AnimeService.CreateAnime:input_type -> otaku.anime.CreateAnimeRequest
	7,  // 8: otaku.anime.AnimeService.GetAnime:input_type -> otaku.anime.GetAnimeRequest
	9,  // 9: otaku.anime.AnimeService.UpdateAnime:input_type -> otaku.anime.UpdateAnimeRequest
	10, // 10: otaku.anime.AnimeService.DeleteAnime:input_type -> otaku.anime.DeleteAnimeRequest
	4,  // 11: otaku.anime.AnimeService.ListAnimes:output_type -> otaku.anime.ListAnimesResponse
	6,  // 12: otaku.anime.AnimeService.CreateAnime:output_type -> otaku.anime.CreateAnimeResponse
	8,  // 13: otaku.anime.AnimeService.GetAnime:output_type -> otaku.anime.GetAnimeResponse
	2,  // 14: otaku.anime.AnimeService.UpdateAnime:output_type -> otaku.anime.Anime
	11, // 15: otaku.anime.AnimeService.DeleteAnime:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_anime_proto_init() }
func file_anime_proto_init() {
	if File_anime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_anime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Anime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAnimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anime_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_anime_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anime_proto_goTypes,
		DependencyIndexes: file_anime_proto_depIdxs,
		EnumInfos:         file_anime_proto_enumTypes,
		MessageInfos:      file_anime_proto_msgTypes,
	}.Build()
	File_anime_proto = out.File
	file_anime_proto_rawDesc = nil
	file_anime_proto_goTypes = nil
	file_anime_proto_depIdxs = nil
}
